create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null,
  action text not null check (char_length(action) between 1 and 80),
  target_user_id uuid,
  before_state jsonb,
  after_state jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;
revoke all on table public.admin_audit_log from anon, authenticated;
revoke all on sequence public.admin_audit_log_id_seq from anon, authenticated;
create index if not exists admin_audit_log_created_at_idx on public.admin_audit_log(created_at desc);
create index if not exists admin_audit_log_target_user_id_idx on public.admin_audit_log(target_user_id);
